// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package taskstore

import (
	"database/sql"
)

type Candidate struct {
	ID             int64
	MessageID      int64
	Kind           string
	Confidence     sql.NullFloat64
	Target         sql.NullString
	AssigneeRaw    sql.NullString
	JiraAccountID  sql.NullString
	DueDate        sql.NullString
	Summary        sql.NullString
	RelatedJiraKey sql.NullString
	HumanVerdict   sql.NullString
}

type Message struct {
	ID               int64
	Source           string
	SourceID         sql.NullString
	ChannelOrMeeting sql.NullString
	Author           sql.NullString
	Text             string
	ReceivedAt       string
	ThreadID         sql.NullString
	ProjectHint      sql.NullString
}

type Task struct {
	ID              int64
	SourceMessageID sql.NullInt64
	Title           string
	Description     sql.NullString
	Target          string
	Status          string
	JiraKey         sql.NullString
	CreatedAt       string
	ClosedAt        sql.NullString
	LastSyncedAt    sql.NullString
	Tracked         int64
	DueDate         sql.NullString
}

type UserMap struct {
	Source        string
	SourceUserID  string
	JiraAccountID sql.NullString
	DisplayName   sql.NullString
}
