// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package taskstore

import (
	"context"
	"database/sql"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM tasks
`

func (q *Queries) CountTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks
  (source_message_id, title, description, target, status, jira_key,
   created_at, closed_at, last_synced_at, tracked, due_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source_message_id, title, description, target, status, jira_key, created_at, closed_at, last_synced_at, tracked, due_date
`

type CreateTaskParams struct {
	SourceMessageID sql.NullInt64
	Title           string
	Description     sql.NullString
	Target          string
	Status          string
	JiraKey         sql.NullString
	CreatedAt       string
	ClosedAt        sql.NullString
	LastSyncedAt    sql.NullString
	Tracked         int64
	DueDate         sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.SourceMessageID,
		arg.Title,
		arg.Description,
		arg.Target,
		arg.Status,
		arg.JiraKey,
		arg.CreatedAt,
		arg.ClosedAt,
		arg.LastSyncedAt,
		arg.Tracked,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SourceMessageID,
		&i.Title,
		&i.Description,
		&i.Target,
		&i.Status,
		&i.JiraKey,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.LastSyncedAt,
		&i.Tracked,
		&i.DueDate,
	)
	return i, err
}

const deleteAllCandidates = `-- name: DeleteAllCandidates :exec
DELETE FROM candidates
`

func (q *Queries) DeleteAllCandidates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCandidates)
	return err
}

const deleteAllMessages = `-- name: DeleteAllMessages :exec
DELETE FROM messages
`

func (q *Queries) DeleteAllMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMessages)
	return err
}

const deleteAllTasks = `-- name: DeleteAllTasks :exec
DELETE FROM tasks
`

func (q *Queries) DeleteAllTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTasks)
	return err
}

const deleteAllUserMap = `-- name: DeleteAllUserMap :exec
DELETE FROM user_map
`

func (q *Queries) DeleteAllUserMap(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserMap)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, source_message_id, title, description, target, status, jira_key, created_at, closed_at, last_synced_at, tracked, due_date FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SourceMessageID,
		&i.Title,
		&i.Description,
		&i.Target,
		&i.Status,
		&i.JiraKey,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.LastSyncedAt,
		&i.Tracked,
		&i.DueDate,
	)
	return i, err
}

const insertCandidate = `-- name: InsertCandidate :exec
INSERT INTO candidates (message_id, kind, confidence, target, assignee_raw, jira_account_id, due_date, summary, related_jira_key, human_verdict)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCandidateParams struct {
	MessageID      int64
	Kind           string
	Confidence     sql.NullFloat64
	Target         sql.NullString
	AssigneeRaw    sql.NullString
	JiraAccountID  sql.NullString
	DueDate        sql.NullString
	Summary        sql.NullString
	RelatedJiraKey sql.NullString
	HumanVerdict   sql.NullString
}

func (q *Queries) InsertCandidate(ctx context.Context, arg InsertCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertCandidate,
		arg.MessageID,
		arg.Kind,
		arg.Confidence,
		arg.Target,
		arg.AssigneeRaw,
		arg.JiraAccountID,
		arg.DueDate,
		arg.Summary,
		arg.RelatedJiraKey,
		arg.HumanVerdict,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (source, source_id, channel_or_meeting, author, text, received_at, thread_id, project_hint)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertMessageParams struct {
	Source           string
	SourceID         sql.NullString
	ChannelOrMeeting sql.NullString
	Author           sql.NullString
	Text             string
	ReceivedAt       string
	ThreadID         sql.NullString
	ProjectHint      sql.NullString
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.Source,
		arg.SourceID,
		arg.ChannelOrMeeting,
		arg.Author,
		arg.Text,
		arg.ReceivedAt,
		arg.ThreadID,
		arg.ProjectHint,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUserMap = `-- name: InsertUserMap :exec
INSERT INTO user_map (source, source_user_id, jira_account_id, display_name)
VALUES (?, ?, ?, ?)
`

type InsertUserMapParams struct {
	Source        string
	SourceUserID  string
	JiraAccountID sql.NullString
	DisplayName   sql.NullString
}

func (q *Queries) InsertUserMap(ctx context.Context, arg InsertUserMapParams) error {
	_, err := q.db.ExecContext(ctx, insertUserMap,
		arg.Source,
		arg.SourceUserID,
		arg.JiraAccountID,
		arg.DisplayName,
	)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT tasks.id, tasks.source_message_id, tasks.title, tasks.description, tasks.target, tasks.status, tasks.jira_key, tasks.created_at, tasks.closed_at, tasks.last_synced_at, tasks.tracked, tasks.due_date,
       messages.source AS msg_source,
       messages.channel_or_meeting AS msg_channel,
       messages.author AS msg_author,
       messages.text AS msg_text,
       messages.received_at AS msg_received_at
FROM tasks
LEFT JOIN messages ON tasks.source_message_id = messages.id
WHERE (?1 IS NULL OR tasks.target = ?1)
  AND (?2 OR tasks.tracked = 1)
ORDER BY tasks.created_at DESC
`

type ListTasksParams struct {
	Target        interface{}
	ShowUntracked interface{}
}

type ListTasksRow struct {
	ID              int64
	SourceMessageID sql.NullInt64
	Title           string
	Description     sql.NullString
	Target          string
	Status          string
	JiraKey         sql.NullString
	CreatedAt       string
	ClosedAt        sql.NullString
	LastSyncedAt    sql.NullString
	Tracked         int64
	DueDate         sql.NullString
	MsgSource       sql.NullString
	MsgChannel      sql.NullString
	MsgAuthor       sql.NullString
	MsgText         sql.NullString
	MsgReceivedAt   sql.NullString
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.Target, arg.ShowUntracked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceMessageID,
			&i.Title,
			&i.Description,
			&i.Target,
			&i.Status,
			&i.JiraKey,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.LastSyncedAt,
			&i.Tracked,
			&i.DueDate,
			&i.MsgSource,
			&i.MsgChannel,
			&i.MsgAuthor,
			&i.MsgText,
			&i.MsgReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskTracked = `-- name: SetTaskTracked :exec
UPDATE tasks SET tracked = 1 WHERE id = ?
`

func (q *Queries) SetTaskTracked(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setTaskTracked, id)
	return err
}

const setTaskTrackedAndSynced = `-- name: SetTaskTrackedAndSynced :exec
UPDATE tasks SET tracked = 1, last_synced_at = ? WHERE id = ?
`

type SetTaskTrackedAndSyncedParams struct {
	LastSyncedAt sql.NullString
	ID           int64
}

func (q *Queries) SetTaskTrackedAndSynced(ctx context.Context, arg SetTaskTrackedAndSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setTaskTrackedAndSynced, arg.LastSyncedAt, arg.ID)
	return err
}

const setTaskUntrackedAsDone = `-- name: SetTaskUntrackedAsDone :exec
UPDATE tasks SET tracked = 0, status = 'done', closed_at = ? WHERE id = ?
`

type SetTaskUntrackedAsDoneParams struct {
	ClosedAt sql.NullString
	ID       int64
}

func (q *Queries) SetTaskUntrackedAsDone(ctx context.Context, arg SetTaskUntrackedAsDoneParams) error {
	_, err := q.db.ExecContext(ctx, setTaskUntrackedAsDone, arg.ClosedAt, arg.ID)
	return err
}

const setTaskUntrackedKeepStatus = `-- name: SetTaskUntrackedKeepStatus :exec
UPDATE tasks SET tracked = 0 WHERE id = ?
`

func (q *Queries) SetTaskUntrackedKeepStatus(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setTaskUntrackedKeepStatus, id)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET title = ?, description = ?, target = ?,
                 status = ?, closed_at = ?, due_date = ? WHERE id = ?
`

type UpdateTaskParams struct {
	Title       string
	Description sql.NullString
	Target      string
	Status      string
	ClosedAt    sql.NullString
	DueDate     sql.NullString
	ID          int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Target,
		arg.Status,
		arg.ClosedAt,
		arg.DueDate,
		arg.ID,
	)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ?, closed_at = ? WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status   string
	ClosedAt sql.NullString
	ID       int64
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ClosedAt, arg.ID)
	return err
}
